/**
 * @fileoverview gRPC-Web generated client stub for testGrpc
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.6.1
// source: proto/test_grpc.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as proto_test_grpc_pb from '../proto/test_grpc_pb';


export class testGrpcServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptortestUnary = new grpcWeb.MethodDescriptor(
    '/testGrpc.testGrpcService/testUnary',
    grpcWeb.MethodType.UNARY,
    proto_test_grpc_pb.testRequest,
    proto_test_grpc_pb.testResponse,
    (request: proto_test_grpc_pb.testRequest) => {
      return request.serializeBinary();
    },
    proto_test_grpc_pb.testResponse.deserializeBinary
  );

  testUnary(
    request: proto_test_grpc_pb.testRequest,
    metadata: grpcWeb.Metadata | null): Promise<proto_test_grpc_pb.testResponse>;

  testUnary(
    request: proto_test_grpc_pb.testRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_test_grpc_pb.testResponse) => void): grpcWeb.ClientReadableStream<proto_test_grpc_pb.testResponse>;

  testUnary(
    request: proto_test_grpc_pb.testRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_test_grpc_pb.testResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/testGrpc.testGrpcService/testUnary',
        request,
        metadata || {},
        this.methodDescriptortestUnary,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/testGrpc.testGrpcService/testUnary',
    request,
    metadata || {},
    this.methodDescriptortestUnary);
  }

  methodDescriptortestStreaming = new grpcWeb.MethodDescriptor(
    '/testGrpc.testGrpcService/testStreaming',
    grpcWeb.MethodType.UNARY,
    proto_test_grpc_pb.testStreamRequest,
    proto_test_grpc_pb.testResponse,
    (request: proto_test_grpc_pb.testStreamRequest) => {
      return request.serializeBinary();
    },
    proto_test_grpc_pb.testResponse.deserializeBinary
  );

  testStreaming(
    request: proto_test_grpc_pb.testStreamRequest,
    metadata: grpcWeb.Metadata | null): Promise<proto_test_grpc_pb.testResponse>;

  testStreaming(
    request: proto_test_grpc_pb.testStreamRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_test_grpc_pb.testResponse) => void): grpcWeb.ClientReadableStream<proto_test_grpc_pb.testResponse>;

  testStreaming(
    request: proto_test_grpc_pb.testStreamRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_test_grpc_pb.testResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/testGrpc.testGrpcService/testStreaming',
        request,
        metadata || {},
        this.methodDescriptortestStreaming,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/testGrpc.testGrpcService/testStreaming',
    request,
    metadata || {},
    this.methodDescriptortestStreaming);
  }

}

