/**
 * @fileoverview gRPC-Web generated client stub for testGrpc
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.6.1
// source: proto/test_grpc.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.testGrpc = require('./test_grpc_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.testGrpc.testGrpcServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.testGrpc.testGrpcServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.testGrpc.testRequest,
 *   !proto.testGrpc.testResponse>}
 */
const methodDescriptor_testGrpcService_testUnary = new grpc.web.MethodDescriptor(
  '/testGrpc.testGrpcService/testUnary',
  grpc.web.MethodType.UNARY,
  proto.testGrpc.testRequest,
  proto.testGrpc.testResponse,
  /**
   * @param {!proto.testGrpc.testRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.testGrpc.testResponse.deserializeBinary
);


/**
 * @param {!proto.testGrpc.testRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.testGrpc.testResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.testGrpc.testResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.testGrpc.testGrpcServiceClient.prototype.testUnary =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/testGrpc.testGrpcService/testUnary',
      request,
      metadata || {},
      methodDescriptor_testGrpcService_testUnary,
      callback);
};


/**
 * @param {!proto.testGrpc.testRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.testGrpc.testResponse>}
 *     Promise that resolves to the response
 */
proto.testGrpc.testGrpcServicePromiseClient.prototype.testUnary =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/testGrpc.testGrpcService/testUnary',
      request,
      metadata || {},
      methodDescriptor_testGrpcService_testUnary);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.testGrpc.testStreamRequest,
 *   !proto.testGrpc.testResponse>}
 */
const methodDescriptor_testGrpcService_testStreaming = new grpc.web.MethodDescriptor(
  '/testGrpc.testGrpcService/testStreaming',
  grpc.web.MethodType.UNARY,
  proto.testGrpc.testStreamRequest,
  proto.testGrpc.testResponse,
  /**
   * @param {!proto.testGrpc.testStreamRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.testGrpc.testResponse.deserializeBinary
);


/**
 * @param {!proto.testGrpc.testStreamRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.testGrpc.testResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.testGrpc.testResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.testGrpc.testGrpcServiceClient.prototype.testStreaming =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/testGrpc.testGrpcService/testStreaming',
      request,
      metadata || {},
      methodDescriptor_testGrpcService_testStreaming,
      callback);
};


/**
 * @param {!proto.testGrpc.testStreamRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.testGrpc.testResponse>}
 *     Promise that resolves to the response
 */
proto.testGrpc.testGrpcServicePromiseClient.prototype.testStreaming =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/testGrpc.testGrpcService/testStreaming',
      request,
      metadata || {},
      methodDescriptor_testGrpcService_testStreaming);
};


module.exports = proto.testGrpc;

