apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-mongodb-scripts
  namespace: dev
data:
  custom-setup.sh: |-
    #!/bin/bash
    
    # # Modify this section at your will
    # if [[ "$MY_POD_NAME" = "mongodb-replica-0" ]]; then
    #     echo "Pod name matches initial primary pod name, configuring node as a primary"
    #     export MONGODB_REPLICA_SET_MODE="primary"
    # else
    #     echo "Pod name doesn't match initial primary pod name, configuring node as a secondary"
    #     export MONGODB_REPLICA_SET_MODE="secondary"
    #     export MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD="$MONGODB_ROOT_PASSWORD"
    #     export MONGODB_INITIAL_PRIMARY_PORT_NUMBER="$MONGODB_PORT_NUMBER"
    #     export MONGODB_ROOT_PASSWORD="" MONGODB_USERNAME="" MONGODB_DATABASE="" MONGODB_PASSWORD=""
    #     export MONGODB_ROOT_PASSWORD_FILE="" MONGODB_USERNAME_FILE="" MONGODB_DATABASE_FILE="" MONGODB_PASSWORD_FILE=""
    # fi